travis:
  secure:
    BINSTAR_TOKEN: Su7toZgdKMPlhMy7MOkGwmSHd+kD1y6mcH2m5Yrr7m5rTGoA52klrTMjPRtc7e/rsQak4tJ593r6VRgvcewzMFh0PmDq88ifpS768h37BtSiL2RTCCzPNSVtz8zH7Y1eAlW7BnkhugtSfqlyIdfTZKdaUMh6BPaBqjcpsgJSHBt6Kmd0O18822IBOa4YhKmj4BKCcrugsWYdzO5Z/ktr/pV7rVs7hRdCRKnzo9Wclz/ipqnOGAicypgtB4EX8F1dT0hYfptwK+HozDgXZiMBfeWRZoWWMjIX1t5KPINS5yXOPMM3wRzi1SQCfBN3sngrYZAjOf0YlIOu+NXsTRV1T9JMfwsHqTmBx6qN/T2lan4d3w3hB1l4b8yj43tXtzKp1fmPJMKX927LPSyOKq4vuRO2w5rvxM2BSgZ4cf5ekWUar10vN099UzLnTiYL8i0E/5N08OD3GJ8SOa5tMBRC7VVphteTVoJDKtuAXsAUDfx4DySKxDwmL8Px7OnsSrWPVBlDWdONijmTXQ+fjoojGyjvbbjDfFHdaYKycfsIervveX1iI1AaL2j5pxXfLjrd7EH8Zy1evASfjJiMeDwuArx+zFUSNO73YNDJRHZSaLcCCHGdO130lVjYqSqPBloFiW15C5epV4wRIXt65DPbn6VTHd3YakqHhO74wijnNaQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
