travis:
  secure:
    BINSTAR_TOKEN: LsbyJt/Txi8BL/mFDB+aOdfJp5E1i3kSEOk1ITyHLH980kxsR+znbk25gav2cZHC4L7PKrYuXJcNOtzqx/K9cdKzRuB3OW00qUnMIAbT7sNSvIxdFwzVgHuFTH/aWHr4LRV+mxQahI+u/Peh8KemaneP0oXPp/1K+m9OQEL1NQadswCRNPoWjPH/G1pmI9cZGokp8MME+J4yoPNPy5NNKptv3mFwoFr1LKz/hWrNve4Qrsu/vaXi+GeKuf7a9FMUaYoxM3CAw7TBHb6sO/LtSPNpF1gOCyJa3YEzdpREC5++wBkoCvhvgO0/rkrXADf7I2uQAMnZ3xDy6W5ic5mXyfcpXGTMAE9L/9mJrdK0p/zmi88GQiI9HzJz5Q88nKRHts7Pc1mpgr9J0g5Uevx1JxGag8RspLiCunxi6ogwMp/RmJGQ39THy+/ebB+i5UN2nyPW5Yvqn+y350U+M7ypZmrvwhLwxlsnMTX4x+LoKzjBmq8xb8tjbwNliQbqS4D+O5dU2h93Bz3WyVQVFlRW9f/RDhiivp/cSfd1cazLWaPNpOOcP6FLB8XiIQotlMhe4qZ/rX+DA4EGW7Ka+Ngj/tPHrEu/SPPXZdlZ+nMhKPB9a0GcYJgBPGRedr4F1VhwLCrNPBSbpA5mZAh8sSr2C32VF2mPL/qupsT4tFYjhuw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
